//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxCalculator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxAmount
    {

        public TaxAmount()
        {

            DateTime = DateTime.Now;
        }

        public int Id { get; set; }
        public DateTime DateTime { get; private set; }
        public string PostalCode { get; set; }
        public decimal TaxIncome { get; set; }
        public decimal CalculatedValue { get; set; }
    }
}
